version: '3.4'

networks:
  net:
    driver: bridge

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - net

  chatgpt:
    image: pawanosman/chatgpt:latest
    ports:
      - "3040:3040"

volumes:
  mongodb_data_container:
  chroma-data:
    driver: local
