version: '3.4'

networks:
  net:
    driver: bridge

services:
  # flask:
  #   restart: always
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - IS_PERSISTENT=TRUE
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   networks:
  #     - net
  #   depends_on:
  #     - chroma
  #     - mongodb

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    networks:
      - net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - net

  # nginx:
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - flask
  #   networks:
  #     - net

volumes:
  mongodb_data_container:
  chroma-data:
    driver: local
